services:
  evolver:
    build:
      context: .
      args:
        USER_ID: ${LOCAL_UID:-1000}
        GROUP_ID: ${LOCAL_GID:-1000}
    volumes:
      - .:/app
      - ../drupal:/drupal:ro
      - ./.cache/composer:/home/evolver/.composer/cache
    environment:
      EVOLVER_DB: /app/.data/evolver.sqlite
      EVOLVER_GRAMMAR_PATH: /usr/lib
    entrypoint: ["php", "bin/evolver"]
